export type ScenarioData = {
  parcel_id: string;
  ulpin: string;
  survey_number: string;
  plot_number: string;
  holder_name: string;
  area: string;
  normalized_area_sqm: number;
  village: string;
  taluk: string;
  district: string;
  state: string;
  pincode: string;
  land_use: string;
  scenario: string;
  expected_result: "MATCH" | "PARTIAL_MATCH" | "REVIEW_REQUIRED";
  notes: string;
  doc_name: string;
  doc_area: string;
  doc_holder: string;
  doc_survey: string;
  doc_type: string;
  confidence: number;
  priority: string;
  reason: string;
  discrepancy_field?: string;
};

export const SYNTHETIC_SCENARIOS: ScenarioData[] = [
  {
    parcel_id: "SYN-PARCEL-001",
    ulpin: "SYN-ULPIN-KA-000001",
    survey_number: "101/1",
    plot_number: "4A",
    holder_name: "Arjun Rao",
    area: "2.40 acre",
    normalized_area_sqm: 9712.46,
    village: "Sample Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560001",
    land_use: "Agricultural",
    scenario: "Case 1: Fully Consistent (MATCH)",
    expected_result: "MATCH",
    notes: "All extracted values match authority record perfectly.",
    doc_name: "Record of Rights (RTC)",
    doc_area: "2.40 acre",
    doc_holder: "Arjun Rao",
    doc_survey: "101/1",
    doc_type: "Record of Rights",
    confidence: 0.98,
    priority: "NONE",
    reason: "Consistent record across deed and authority extract."
  },
  {
    parcel_id: "SYN-PARCEL-002",
    ulpin: "SYN-ULPIN-KA-000002",
    survey_number: "124/2",
    plot_number: "18B",
    holder_name: "Ramesh Kumar",
    area: "2.40 acre",
    normalized_area_sqm: 9712.46,
    village: "Sampurna Village",
    taluk: "Model Tehsil",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560002",
    land_use: "Agricultural",
    scenario: "Case 2: Area Mismatch (0.09 Acre Variance)",
    expected_result: "REVIEW_REQUIRED",
    notes: "Document reports 2.31 acres while authority states 2.40 acres (0.09 acre / ~364 m² variance).",
    doc_name: "Registered Sale Deed No. 4412/2018",
    doc_area: "2.31 acre",
    doc_holder: "Ramesh Kumar",
    doc_survey: "124/2",
    doc_type: "Registered Sale Deed",
    confidence: 0.88,
    priority: "P2_NORMAL",
    reason: "Area variance of 0.09 acre (~364 m²) detected between deed and authority record.",
    discrepancy_field: "area"
  },
  {
    parcel_id: "SYN-PARCEL-003",
    ulpin: "SYN-ULPIN-KA-000003",
    survey_number: "158/4",
    plot_number: "12C",
    holder_name: "Meera Rao",
    area: "1.85 acre",
    normalized_area_sqm: 7486.68,
    village: "Sample Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560003",
    land_use: "Agricultural",
    scenario: "Case 3: Owner Name Mismatch (Nair vs Rao)",
    expected_result: "REVIEW_REQUIRED",
    notes: "Document holder is Meera Nair, but authority states Meera Rao.",
    doc_name: "Sale Deed No. 1092/2019",
    doc_area: "1.85 acre",
    doc_holder: "Meera Nair",
    doc_survey: "158/4",
    doc_type: "Sale Deed",
    confidence: 0.96,
    priority: "P1_HIGH",
    reason: "Holder name differs between submitted deed ('Meera Nair') and authority extract ('Meera Rao').",
    discrepancy_field: "owner"
  },
  {
    parcel_id: "SYN-PARCEL-004",
    ulpin: "SYN-ULPIN-KA-000004",
    survey_number: "204/8",
    plot_number: "7",
    holder_name: "Kiran Shetty",
    area: "3.10 acre",
    normalized_area_sqm: 12545.25,
    village: "Greenfield Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560004",
    land_use: "Agricultural",
    scenario: "Case 4: Survey Number Mismatch (204/3 vs 204/8)",
    expected_result: "REVIEW_REQUIRED",
    notes: "Document reports survey 204/3 while authority states 204/8.",
    doc_name: "Partition Deed 2020",
    doc_area: "3.10 acre",
    doc_holder: "Kiran Shetty",
    doc_survey: "204/3",
    doc_type: "Partition Deed",
    confidence: 0.97,
    priority: "P1_HIGH",
    reason: "Survey number discrepancy: Deed cites '204/3' while authority record specifies '204/8'.",
    discrepancy_field: "survey_number"
  },
  {
    parcel_id: "SYN-PARCEL-005",
    ulpin: "SYN-ULPIN-KA-000005",
    survey_number: "77/1",
    plot_number: "3",
    holder_name: "Ananya Iyer",
    area: "1.25 acre",
    normalized_area_sqm: 5058.57,
    village: "Sample Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560005",
    land_use: "Agricultural",
    scenario: "Case 5: Missing Extent Field in Document",
    expected_result: "REVIEW_REQUIRED",
    notes: "Deed schedule is torn/faded; area is MISSING from document extraction.",
    doc_name: "Faded Settlement Extract",
    doc_area: "NOT_AVAILABLE",
    doc_holder: "Ananya Iyer",
    doc_survey: "77/1",
    doc_type: "Faded Settlement Extract",
    confidence: 0.85,
    priority: "P2_NORMAL",
    reason: "Essential extent attribute missing from uploaded document extraction.",
    discrepancy_field: "area"
  },
  {
    parcel_id: "SYN-PARCEL-006",
    ulpin: "SYN-ULPIN-KA-000006",
    survey_number: "318/2",
    plot_number: "14",
    holder_name: "Rohan Kulkarni",
    area: "4.20 acre",
    normalized_area_sqm: 16996.80,
    village: "Adarsh Nagar",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560006",
    land_use: "Agricultural",
    scenario: "Case 6: Low OCR Confidence (318/? @ 51%)",
    expected_result: "REVIEW_REQUIRED",
    notes: "Survey number extracted as 318/? with low confidence 0.51.",
    doc_name: "Faded Certified Copy",
    doc_area: "4.20 acre",
    doc_holder: "Rohan Kulkarni",
    doc_survey: "318/?",
    doc_type: "Faded Certified Copy",
    confidence: 0.51,
    priority: "P2_NORMAL",
    reason: "Extraction confidence of 51% falls below the 80% automated validation threshold.",
    discrepancy_field: "survey_number"
  },
  {
    parcel_id: "SYN-PARCEL-007",
    ulpin: "SYN-ULPIN-KA-000007",
    survey_number: "89/1A",
    plot_number: "5",
    holder_name: "Vikram Sharma",
    area: "0.95 acre",
    normalized_area_sqm: 3844.51,
    village: "Sample Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560007",
    land_use: "Agricultural",
    scenario: "Case 7: Partial Name Match (Parentage/Honorific)",
    expected_result: "PARTIAL_MATCH",
    notes: "Name includes parentage 'Vikram Sharma S/o Devendra Sharma' matching 'Vikram Sharma'.",
    doc_name: "Sale Deed No. 892/2021",
    doc_area: "0.95 acre",
    doc_holder: "Vikram Sharma S/o Devendra Sharma",
    doc_survey: "89/1A",
    doc_type: "Sale Deed",
    confidence: 0.94,
    priority: "P3_ADVISORY",
    reason: "Partial match on holder name: parentage honorific present in submitted deed."
  },
  {
    parcel_id: "SYN-PARCEL-008",
    ulpin: "SYN-ULPIN-KA-000008",
    survey_number: "112/5",
    plot_number: "9",
    holder_name: "Sneha Patil",
    area: "2.00 acre",
    normalized_area_sqm: 8093.71,
    village: "Sample Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560008",
    land_use: "Agricultural",
    scenario: "Case 8: Boundary / Spatial Review (7.8m Edge Delta)",
    expected_result: "REVIEW_REQUIRED",
    notes: "Sketch CV detects 192.8m eastern edge vs 185.0m authoritative cadastral footprint.",
    doc_name: "Land Cadastral Sketch Blueprint",
    doc_area: "2.00 acre",
    doc_holder: "Sneha Patil",
    doc_survey: "112/5",
    doc_type: "Land Cadastral Sketch Blueprint",
    confidence: 0.86,
    priority: "P2_NORMAL",
    reason: "Spatial discrepancy: Sketch boundary detects 7.8m variance along eastern edge.",
    discrepancy_field: "boundaries"
  },
  {
    parcel_id: "SYN-PARCEL-009",
    ulpin: "SYN-ULPIN-KA-000009",
    survey_number: "64/3",
    plot_number: "21",
    holder_name: "Rajesh Gowda",
    area: "3.50 acre",
    normalized_area_sqm: 14164.00,
    village: "Vikas Nagar",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560009",
    land_use: "Agricultural",
    scenario: "Case 9: Multiple Documents (Deed + RTC + Sketch)",
    expected_result: "MATCH",
    notes: "4 associated documents: RoR, Sale Deed, FMB Survey Sketch, and Mutation Sanction.",
    doc_name: "Multi-Document Dossier (4 Docs)",
    doc_area: "3.50 acre",
    doc_holder: "Rajesh Gowda",
    doc_survey: "64/3",
    doc_type: "Multi-Document Bundle",
    confidence: 0.97,
    priority: "NONE",
    reason: "All 4 cross-document evidences confirm consistent title extent and geometry."
  },
  {
    parcel_id: "SYN-PARCEL-010",
    ulpin: "SYN-ULPIN-KA-000010",
    survey_number: "140/2",
    plot_number: "11",
    holder_name: "Divya Menon",
    area: "2.75 acre",
    normalized_area_sqm: 11128.85,
    village: "Sample Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560010",
    land_use: "Agricultural",
    scenario: "Case 10: Complete Mutation History (1994–2024)",
    expected_result: "MATCH",
    notes: "Traces 3 historical mutations: 1994 Partition, 2012 Succession, 2024 Gift Deed.",
    doc_name: "Registered Gift Deed No. 120/2024",
    doc_area: "2.75 acre",
    doc_holder: "Divya Menon",
    doc_survey: "140/2",
    doc_type: "Registered Gift Deed",
    confidence: 0.98,
    priority: "NONE",
    reason: "Deed matches latest sanctioned mutation entry MR-89/2024."
  },
  {
    parcel_id: "SYN-PARCEL-011",
    ulpin: "SYN-ULPIN-KA-000011",
    survey_number: "99/1",
    plot_number: "16",
    holder_name: "Suresh Deshmukh",
    area: "1.50 acre",
    normalized_area_sqm: 6070.28,
    village: "Sample Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560011",
    land_use: "Agricultural",
    scenario: "Case 11: Duplicate Document Upload (SHA-256 Match)",
    expected_result: "MATCH",
    notes: "Identical deed uploaded twice; system flags duplicate SHA-256 hash.",
    doc_name: "Sale Deed (Duplicate Content)",
    doc_area: "1.50 acre",
    doc_holder: "Suresh Deshmukh",
    doc_survey: "99/1",
    doc_type: "Sale Deed",
    confidence: 0.99,
    priority: "P3_ADVISORY",
    reason: "Duplicate file upload detected via SHA-256 integrity match."
  },
  {
    parcel_id: "SYN-PARCEL-012",
    ulpin: "SYN-ULPIN-KA-000012",
    survey_number: "215/6",
    plot_number: "8",
    holder_name: "Kavita Reddy",
    area: "1.80 acre",
    normalized_area_sqm: 7284.34,
    village: "Demo Hamlet",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560012",
    land_use: "Agricultural",
    scenario: "Case 12: Ambiguous Land Unit ('2.5 Local Bigha' - Rule 13)",
    expected_result: "REVIEW_REQUIRED",
    notes: "Deed specifies '2.5 local bigha'; Rule 13 prohibits automated conversion.",
    doc_name: "Old Revenue Extract",
    doc_area: "2.5 local bigha",
    doc_holder: "Kavita Reddy",
    doc_survey: "215/6",
    doc_type: "Old Revenue Extract",
    confidence: 0.91,
    priority: "P1_HIGH",
    reason: "Regional unit 'bigha' lacks state-level metric schedule. Automated conversion blocked.",
    discrepancy_field: "area"
  },
  {
    parcel_id: "SYN-PARCEL-013",
    ulpin: "SYN-ULPIN-KA-000013",
    survey_number: "52/1",
    plot_number: "2",
    holder_name: "Amit Joshi",
    area: "2.10 acre",
    normalized_area_sqm: 8498.40,
    village: "Sample Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560013",
    land_use: "Agricultural",
    scenario: "Case 13: Co-Ownership / Share Discrepancy",
    expected_result: "REVIEW_REQUIRED",
    notes: "Deed lists joint co-parceners (Amit & Sumit Joshi) while authority lists sole holder.",
    doc_name: "Family Settlement Deed",
    doc_area: "2.10 acre",
    doc_holder: "Amit Joshi & Sumit Joshi (Co-parceners)",
    doc_survey: "52/1",
    doc_type: "Family Settlement Deed",
    confidence: 0.93,
    priority: "P2_NORMAL",
    reason: "Undivided joint share claim in deed vs sole khatedar in revenue register.",
    discrepancy_field: "owner"
  },
  {
    parcel_id: "SYN-PARCEL-014",
    ulpin: "SYN-ULPIN-KA-000014",
    survey_number: "180/7",
    plot_number: "15",
    holder_name: "Priya Swaminathan",
    area: "1.10 acre",
    normalized_area_sqm: 4451.54,
    village: "Sample Village",
    taluk: "Demo Taluk",
    district: "Synthetic District",
    state: "Karnataka",
    pincode: "560014",
    land_use: "Agricultural",
    scenario: "Case 14: Land Use Conflict (Commercial NA vs Agricultural)",
    expected_result: "REVIEW_REQUIRED",
    notes: "Deed asserts Commercial/Industrial Non-Agricultural (NA), but authority records Agricultural.",
    doc_name: "Commercial Lease / Sale Deed",
    doc_area: "1.10 acre",
    doc_holder: "Priya Swaminathan",
    doc_survey: "180/7",
    doc_type: "Commercial Lease Deed",
    confidence: 0.95,
    priority: "P1_HIGH",
    reason: "Unsanctioned land conversion: Deed claims Commercial use without DC NA conversion order.",
    discrepancy_field: "land_use"
  }
];
