"""initial_schema

Revision ID: 859e7fd7d564
Revises: 
Create Date: 2026-09-27 21:11:13.621982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '859e7fd7d564'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('before_state', sa.JSON(), nullable=True),
    sa.Column('after_state', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_events_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_timestamp'), 'audit_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_events_trace_id'), 'audit_events', ['trace_id'], unique=False)
    op.create_table('land_parcels',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ulpin', sa.String(length=64), nullable=False),
    sa.Column('survey_number', sa.String(length=64), nullable=False),
    sa.Column('plot_number', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('area', sa.String(length=64), nullable=False),
    sa.Column('area_unit', sa.String(length=32), nullable=False),
    sa.Column('normalized_area_sqm', sa.Float(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('tehsil', sa.String(length=128), nullable=False),
    sa.Column('village', sa.String(length=128), nullable=False),
    sa.Column('land_use', sa.String(length=64), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('geometry_source', sa.String(length=256), nullable=False),
    sa.Column('authoritative_source', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_parcels_survey_village', 'land_parcels', ['survey_number', 'village'], unique=False)
    op.create_index(op.f('ix_land_parcels_owner'), 'land_parcels', ['owner'], unique=False)
    op.create_index(op.f('ix_land_parcels_plot_number'), 'land_parcels', ['plot_number'], unique=False)
    op.create_index(op.f('ix_land_parcels_survey_number'), 'land_parcels', ['survey_number'], unique=False)
    op.create_index(op.f('ix_land_parcels_ulpin'), 'land_parcels', ['ulpin'], unique=True)
    op.create_index(op.f('ix_land_parcels_village'), 'land_parcels', ['village'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('jurisdiction', sa.String(length=256), nullable=True),
    sa.Column('permitted_parcels', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=128), nullable=False),
    sa.Column('original_file_name', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.String(length=128), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_parcel_id'), 'documents', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_table('mutation_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=False),
    sa.Column('mutation_number', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('recorded_date', sa.String(length=32), nullable=False),
    sa.Column('parties_involved', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order_reference', sa.String(length=256), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mutation_events_mutation_number'), 'mutation_events', ['mutation_number'], unique=False)
    op.create_index(op.f('ix_mutation_events_parcel_id'), 'mutation_events', ['parcel_id'], unique=False)
    op.create_table('ownership_relationships',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=False),
    sa.Column('holder_name', sa.String(length=256), nullable=False),
    sa.Column('share_extent', sa.String(length=64), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('recorded_date', sa.String(length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=256), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ownership_relationships_holder_name'), 'ownership_relationships', ['holder_name'], unique=False)
    op.create_index(op.f('ix_ownership_relationships_parcel_id'), 'ownership_relationships', ['parcel_id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_document_id'), 'extractions', ['document_id'], unique=True)
    op.create_table('review_cases',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.String(length=32), nullable=False),
    sa.Column('discrepancy_field', sa.String(length=64), nullable=True),
    sa.Column('claimed_value', sa.Text(), nullable=True),
    sa.Column('authoritative_value', sa.Text(), nullable=True),
    sa.Column('assigned_officer', sa.String(length=128), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_cases_status_priority', 'review_cases', ['status', 'priority'], unique=False)
    op.create_index(op.f('ix_review_cases_parcel_id'), 'review_cases', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_review_cases_status'), 'review_cases', ['status'], unique=False)
    op.create_table('validation_results',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('parcel_id', sa.String(length=64), nullable=False),
    sa.Column('document_id', sa.String(length=64), nullable=True),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('source_a', sa.String(length=128), nullable=False),
    sa.Column('value_a', sa.Text(), nullable=False),
    sa.Column('source_b', sa.String(length=128), nullable=False),
    sa.Column('value_b', sa.Text(), nullable=False),
    sa.Column('comparison_operator', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parcel_id'], ['land_parcels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_results_document_id'), 'validation_results', ['document_id'], unique=False)
    op.create_index(op.f('ix_validation_results_field'), 'validation_results', ['field'], unique=False)
    op.create_index(op.f('ix_validation_results_parcel_id'), 'validation_results', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_validation_results_result'), 'validation_results', ['result'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('extraction_id', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('extracted_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_location', sa.String(length=256), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('reviewer_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_extraction_id'), 'extracted_fields', ['extraction_id'], unique=False)
    op.create_index(op.f('ix_extracted_fields_field_name'), 'extracted_fields', ['field_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_fields_field_name'), table_name='extracted_fields')
    op.drop_index(op.f('ix_extracted_fields_extraction_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_validation_results_result'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_parcel_id'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_field'), table_name='validation_results')
    op.drop_index(op.f('ix_validation_results_document_id'), table_name='validation_results')
    op.drop_table('validation_results')
    op.drop_index(op.f('ix_review_cases_status'), table_name='review_cases')
    op.drop_index(op.f('ix_review_cases_parcel_id'), table_name='review_cases')
    op.drop_index('idx_review_cases_status_priority', table_name='review_cases')
    op.drop_table('review_cases')
    op.drop_index(op.f('ix_extractions_document_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_ownership_relationships_parcel_id'), table_name='ownership_relationships')
    op.drop_index(op.f('ix_ownership_relationships_holder_name'), table_name='ownership_relationships')
    op.drop_table('ownership_relationships')
    op.drop_index(op.f('ix_mutation_events_parcel_id'), table_name='mutation_events')
    op.drop_index(op.f('ix_mutation_events_mutation_number'), table_name='mutation_events')
    op.drop_table('mutation_events')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_parcel_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_land_parcels_village'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_ulpin'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_survey_number'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_plot_number'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_owner'), table_name='land_parcels')
    op.drop_index('idx_parcels_survey_village', table_name='land_parcels')
    op.drop_table('land_parcels')
    op.drop_index(op.f('ix_audit_events_trace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_timestamp'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('idx_audit_events_entity', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
